eureka:
  client:
    enabled: false

cereebro:
  server:
    system:
      name: marvel
      snitch:
        resources: 
          - 'classpath:/snitches/xmen.json'
          - 'classpath:/snitches/spiderman.json'
 