spring:
  application:
    name: cereebro-server
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false

cereebro:
  server:
    system:
      name: cereebro-system
    snitch:
      resources: 'classpath:/snitches/gambit.json'
