eureka:
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: true
    service-url:
       defaultZone: http://eureka:eureka@localhost:13052/lab-eureka-api/eureka

cereebro:
  server:
    system:
      name: edelia-lab
      
logging:
  level:
    io.cereebro: DEBUG